/**
 * Which URL the public site shows for a vehicle photo.
 *
 * A showroom composite is used only when it is (a) published by an admin and
 * (b) produced by the CURRENT locked showroom template. Composites made with an
 * older template version are ignored on the public site (the original photo is
 * shown instead) and are automatically regenerated by the showroom pipeline —
 * so the catalogue never mixes two different showroom backgrounds.
 *
 * Keep in sync with supabase/functions/_shared/showroomTemplate.ts.
 */
export const SHOWROOM_TEMPLATE = {
  background: "background-v4",
  camera: "camera-v1",
  placement: "placement-v2",
  lighting: "lighting-v2",
} as const;

export type ShowroomImageLike = {
  image_url?: string | null;
  showroom_url?: string | null;
  showroom_applied_at?: string | null;
  showroom_metadata?: unknown;
};

export const isCurrentShowroomTemplate = (meta: unknown): boolean => {
  // Older rows have no metadata at all — treat them as current so a published
  // photo never disappears; the pipeline stamps versions from now on.
  if (!meta || typeof meta !== "object") return true;
  const m = meta as Record<string, unknown>;
  if (!m.background_version) return true;
  return m.background_version === SHOWROOM_TEMPLATE.background
    && m.camera_version === SHOWROOM_TEMPLATE.camera
    && m.placement_version === SHOWROOM_TEMPLATE.placement
    && m.lighting_version === SHOWROOM_TEMPLATE.lighting;
};

export const getPublicVehicleImageUrl = (image: ShowroomImageLike): string => {
  if (image.showroom_applied_at && image.showroom_url && isCurrentShowroomTemplate(image.showroom_metadata)) {
    return image.showroom_url;
  }
  return image.image_url || "";
};
